export const cities = [
  { name: 'Accra Metropolitan ', price: '' },
  { name: 'Achimota', price: '' },
  { name: 'Adabraka', price: '' },
  { name: 'Adenta', price: '25' },
  { name: 'Tema Metropolitan', price: '' },
  { name: 'Abelemkpe', price: '' },
  { name: 'Ablekuma', price: '' },
  { name: 'Abofu', price: '' },
  { name: 'Abokobi', price: '25' },
  { name: 'Abossey Okai', price: '' },
  { name: 'Accra New Town', price: '10' },
  { name: 'Adjiriganor', price: '' },
  { name: 'Agbogba', price: '' },
  { name: 'Agbogbloshie', price: '' },
  { name: 'Airport Residential Area', price: '' },
  { name: 'Akweteyman', price: '' },
  { name: 'Alajo', price: '' },
  { name: 'Amassaman', price: '30' },
  { name: 'Anyaa', price: '' },
  { name: 'Apenkwa', price: '' },
  { name: 'Ashaiman Municipal', price: '35' },
  { name: 'Ashaley Botwe', price: '' },
  { name: 'Ashomang Estate', price: '' },
  { name: 'Asylum Down', price: '' },
  { name: 'Avenor Area', price: '' },
  { name: 'Awoshie', price: '' },
  { name: 'Banana Inn', price: '' },
  { name: 'Bubuashie', price: '20' },
  { name: 'Burma Camp', price: '' },
  { name: 'Cantonments', price: '' },
  { name: 'Chorkor', price: '' },
  { name: 'Circle', price: '' },
  { name: 'Control', price: '' },
  { name: 'Dansoman', price: '25' },
  { name: 'Darkuman', price: '20' },
  { name: 'Dodowa', price: '' },
  { name: 'Dome', price: '' },
  { name: 'Dzorwulu', price: '10' },
  { name: 'East Legon', price: '20' },
  { name: 'East Legon Hills', price: '30' },
  { name: 'Gbawe', price: '' },
  { name: 'Haatso', price: '' },
  { name: 'James Town', price: '' },
  { name: 'Kaneshie', price: '' },
  { name: 'Kokomlemle', price: '10' },
  { name: 'Korle Gonno', price: '' },
  { name: 'Kotobabi', price: '' },
  { name: 'Kwashieman', price: '' },
  { name: 'Labadi', price: '20' },
  { name: 'Labone', price: '20' },
  { name: 'Lapaz', price: '' },
  { name: 'Lartebiokorshie', price: '20' },
  { name: 'Ledzokuku-Krowor', price: '25' },
  { name: 'Madina', price: '25' },
  { name: 'Mamobi', price: '' },
  { name: 'Mamprobi', price: '' },
  { name: 'Mataheko', price: '' },
  { name: 'Nii Boi Town', price: '' },
  { name: 'Nima', price: '10' },
  { name: 'North Industrial Area', price: '' },
  { name: 'Nungua', price: '25' },
  { name: 'Odorkor', price: '' },
  { name: 'Ofankor', price: '' },
  { name: 'Okaishie', price: '' },
  { name: 'Okponglo', price: '20' },
  { name: 'Old Ashomang', price: '' },
  { name: 'Osu', price: '20' },
  { name: 'Oyarifa', price: '' },
  { name: 'Oyibi', price: '' },
  { name: 'Pokuase', price: '30' },
  { name: 'Ridge', price: '' },
  { name: 'Roman Ridge', price: '' },
  { name: 'SSNIT Flats', price: '' },
  { name: 'Santa Maria', price: '25' },
];
